name: BlockParty
version: ${project.parent.version}
description: Official BlockParty Plugin
main: de.leonkoth.blockparty.Main
authors: [Leon167, pauhull]
website: https://github.com/Leon167/BlockParty-2.0/
softdepend: [Multiverse-Core, ReWorld, MCJukebox, NoteBlockAPI, TimoCloud]

commands:
  blockparty:
    aliases: [bp, bparty]
    description: Get information on how to use this Plugin
    usage: /blockparty - to get more information

api-version: 1.13