package de.leonkoth.blockparty.floor;

import de.leonkoth.blockparty.BlockParty;
import de.leonkoth.blockparty.arena.Arena;
import de.leonkoth.blockparty.exception.FloorLoaderException;
import de.leonkoth.blockparty.floor.generator.AreaGenerator;
import de.leonkoth.blockparty.floor.generator.FloorGenerator;
import de.leonkoth.blockparty.floor.generator.SingleBlockGenerator;
import de.leonkoth.blockparty.floor.generator.StripeGenerator;
import de.leonkoth.blockparty.player.PlayerInfo;
import de.leonkoth.blockparty.player.PlayerState;
import de.leonkoth.blockparty.util.Bounds;
import de.leonkoth.blockparty.util.ColorBlock;
import de.leonkoth.blockparty.util.Size;
import de.leonkoth.blockparty.version.BlockPartyMaterial;
import de.leonkoth.blockparty.version.IBlockPlacer;
import de.leonkoth.blockparty.version.VersionedMaterial;
import de.pauhull.utils.particle.ParticlePlayer;
import lombok.Getter;
import lombok.Setter;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.World;
import org.bukkit.block.Block;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;

/**
 * Created by Leon on 14.03.2018.
 * Project Blockparty2
 * © 2016 - Leon Koth
 */
public class Floor {

    private Random random = new Random();

    @Getter
    private Arena arena;

    @Getter
    private World world;

    @Getter
    @Setter
    private Block currentBlock;

    @Getter
    private Size size;

    @Getter
    private Bounds bounds;

    /**
     * Snapshot of the material layout written by the last floor placement,
     * used to pick random blocks without scanning the world.
     */
    private record PlacedFloor(Material[] materials, int width, int length) {
    }

    private PlacedFloor placedFloor;

    private List<Block> floorBlockCache;

    @Setter
    @Getter
    private List<FloorPattern> floorPatterns;

    @Setter
    @Getter
    private List<String> patternNames;

    @Setter
    @Getter
    private List<FloorGenerator> generators = new ArrayList<>();

    public Floor(List<String> patternNames, Bounds bounds, Arena arena, Size size) {
        this.size = size;
        this.arena = arena;
        this.bounds = bounds;
        this.world = bounds.getWorld();
        this.patternNames = patternNames;
        this.floorPatterns = new ArrayList<>();

        for (String name : patternNames) {
            File file = new File(BlockParty.PLUGIN_FOLDER + "Floors/" + name + ".floor");
            try {
                FloorPattern pattern = PatternLoader.readFloorPattern(file);
                floorPatterns.add(pattern);
            } catch (FileNotFoundException | FloorLoaderException e) {
                Bukkit.getConsoleSender().sendMessage("§c[BlockParty] Couldn't find file \"Floors/" + name + ".floor\"");
                BlockParty.getInstance().getPlugin().getLogger().log(Level.FINE, "Could not load floor pattern \"" + name + "\"", e);
            }
        }

        this.generators.add(new AreaGenerator());
        this.generators.add(new SingleBlockGenerator());
        this.generators.add(new StripeGenerator());
    }

    public static boolean create(Arena arena, Bounds bounds) {

        Size size = bounds.getSize();
        List<String> floorNames = new ArrayList<>();

        Floor floor;
        if (arena.getFloor() == null) {
            floor = new Floor(floorNames, bounds, arena, size);
        } else {
            floor = arena.getFloor();
        }

        floor.setSize(size);

        try {
            arena.setFloor(floor);
        } catch (Exception e) {
            BlockParty.getInstance().getPlugin().getLogger().log(Level.SEVERE, "Could not set floor for arena \"" + arena.getName() + "\"", e);
            return false;
        }

        return true;
    }

    public void setWorld(World world) {
        this.world = world;
        invalidateBlockCaches();
    }

    public void setSize(Size size) {
        this.size = size;
        invalidateBlockCaches();
    }

    public void setBounds(Bounds bounds) {
        this.bounds = bounds;
        invalidateBlockCaches();
    }

    private void invalidateBlockCaches() {
        this.floorBlockCache = null;
        this.placedFloor = null;
    }

    public void placeFloor() {
        if (arena.isUsePatternFloors()) {

            if (this.arena.isUseAutoGeneratedFloors()) {
                int index = random.nextInt(floorPatterns.size() + generators.size());

                if (index < floorPatterns.size()) {
                    placePattern(floorPatterns.get(index));
                } else {
                    FloorGenerator generator = generators.get(index - floorPatterns.size());
                    generateFloor(generator);

                    if (BlockParty.DEBUG)
                        Bukkit.getConsoleSender().sendMessage("Using generator: " + generator.getClass().getName());
                }
            } else {
                placePattern(floorPatterns.get(random.nextInt(floorPatterns.size())));
            }

        } else {
            if (!this.arena.isUseAutoGeneratedFloors()) {
                Bukkit.getConsoleSender().sendMessage("§c[BlockParty] UsePatternFloors and UseAutoGeneratedFloors disabled. Using auto generated floors now!");
            }

            generateFloor();
        }
    }

    private void placePattern(FloorPattern pattern) {
        pattern.place(bounds.getA());
        this.placedFloor = new PlacedFloor(pattern.getMaterials(),
                pattern.getSize().getBlockWidth(), pattern.getSize().getBlockLength());
    }

    public void setStartFloor() {
        if (this.arena.isUsePatternFloors()) {

            if (floorPatterns.isEmpty()) {
                generateFloor();
                return;
            }

            for (FloorPattern floorPattern : this.getFloorPatterns()) {
                if (floorPattern.getName().equalsIgnoreCase("start")) {
                    placePattern(floorPattern);
                    return;
                }
            }
            placePattern(floorPatterns.get(random.nextInt(floorPatterns.size())));
        } else {
            generateFloor();
        }
    }

    public void setEndFloor() {
        if (this.arena.isUsePatternFloors()) {

            if (floorPatterns.isEmpty()) {
                generateFloor();
                return;
            }

            for (FloorPattern floorPattern : this.getFloorPatterns()) {
                if (floorPattern.getName().equalsIgnoreCase("end")) {
                    placePattern(floorPattern);
                    return;
                }
            }
            placePattern(floorPatterns.get(random.nextInt(floorPatterns.size())));
        } else {
            generateFloor();
        }
    }

    private void generateFloor() {
        generateFloor(generators.get(random.nextInt(generators.size())));
    }

    private void generateFloor(FloorGenerator generator) {
        BlockPartyMaterial terracotta = VersionedMaterial.TERRACOTTA.get();
        Material[] palette = new Material[16];
        for (int data = 0; data < 16; data++) {
            palette[data] = terracotta.get(data);
        }

        int width = size.getBlockWidth();
        int length = size.getBlockLength();
        Material[] materials = generator.generate(width, length, palette, random);
        applyFloor(materials, width, length);
    }

    private void applyFloor(Material[] materials, int width, int length) {
        IBlockPlacer blockPlacer = BlockParty.getInstance().getBlockPlacer();

        int minX = bounds.getA().getBlockX();
        int y = bounds.getA().getBlockY();
        int minZ = bounds.getA().getBlockZ();

        for (int z = 0; z < length; z++) {
            for (int x = 0; x < width; x++) {
                Material material = materials[x + z * width];
                Block block = world.getBlockAt(minX + x, y, minZ + z);

                if (block.getType() != material) {
                    blockPlacer.place(block, material, (byte) 0, false);
                }
            }
        }

        this.placedFloor = new PlacedFloor(materials, width, length);
    }

    public void removeBlocks() {
        IBlockPlacer blockPlacer = BlockParty.getInstance().getBlockPlacer();
        Material material = currentBlock.getType();

        for (Block block : getFloorBlocks()) {
            if (block.getType() != material) {
                blockPlacer.place(block, Material.AIR, (byte) 0, false);
            }
        }
    }

    public void clear() {
        IBlockPlacer blockPlacer = BlockParty.getInstance().getBlockPlacer();

        for (Block block : getFloorBlocks()) {
            if (block.getType() != Material.AIR) {
                blockPlacer.place(block, Material.AIR, (byte) 0, false);
            }
        }
    }

    public List<Block> getFloorBlocks() {
        if (floorBlockCache != null) {
            return floorBlockCache;
        }

        int minX = bounds.getA().getBlockX();
        int minZ = bounds.getA().getBlockZ();
        int maxX = bounds.getB().getBlockX();
        int maxZ = bounds.getB().getBlockZ();

        List<Block> blocks = new ArrayList<>();

        int y = bounds.getA().getBlockY();
        for (int x = minX; x <= maxX; x++) {
            for (int z = minZ; z <= maxZ; z++) {
                blocks.add(world.getBlockAt(x, y, z));
            }
        }

        this.floorBlockCache = blocks;
        return blocks;
    }

    public void pickBlock() {
        currentBlock = getRandomBlock();
        updateInventories(currentBlock);
    }

    public void updateInventories(Block block) {
        ItemStack stack = new ItemStack(block.getType(), 1);
        ItemMeta meta = stack.getItemMeta();
        String name = ColorBlock.get(block).getName();
        meta.setDisplayName("§f§l§o" + name);
        stack.setItemMeta(meta);

        for (PlayerInfo playerInfo : this.arena.getPlayersInArena()) {
            if (playerInfo.getPlayerState() == PlayerState.INGAME) {
                Player player = playerInfo.asPlayer();

                player.getInventory().setItem(4, stack);
            }
        }
    }

    public void clearInventories() {
        for (PlayerInfo playerInfo : this.arena.getPlayersInArena()) {
            if (playerInfo.getPlayerState() == PlayerState.INGAME) {
                playerInfo.asPlayer().getInventory().clear();
            }
        }
    }

    private Block getRandomBlock() {
        if (placedFloor != null) {
            int index = pickRandomNonAirIndex(placedFloor.materials(), random);
            if (index >= 0) {
                int x = index % placedFloor.width();
                int z = index / placedFloor.width();
                return world.getBlockAt(bounds.getA().getBlockX() + x,
                        bounds.getA().getBlockY(), bounds.getA().getBlockZ() + z);
            }
        }

        // Fallback for floors modified outside placeFloor(): bounded world
        // probing instead of unbounded recursion
        for (int attempt = 0; attempt < 32; attempt++) {
            Block block = getRandomLocation().getBlock();
            if (block.getType() != Material.AIR) {
                return block;
            }
        }

        for (Block block : getFloorBlocks()) {
            if (block.getType() != Material.AIR) {
                return block;
            }
        }

        return getRandomLocation().getBlock();
    }

    static int pickRandomNonAirIndex(Material[] materials, Random random) {
        if (materials.length == 0) {
            return -1;
        }

        for (int attempt = 0; attempt < 8; attempt++) {
            int index = random.nextInt(materials.length);
            if (materials[index] != Material.AIR) {
                return index;
            }
        }

        int nonAir = 0;
        for (Material material : materials) {
            if (material != Material.AIR) {
                nonAir++;
            }
        }

        if (nonAir == 0) {
            return -1;
        }

        int target = random.nextInt(nonAir);
        for (int index = 0; index < materials.length; index++) {
            if (materials[index] != Material.AIR && target-- == 0) {
                return index;
            }
        }

        return -1;
    }

    public Location getRandomLocation() {

        int minX = bounds.getA().getBlockX();
        int minY = bounds.getA().getBlockY();
        int minZ = bounds.getA().getBlockZ();

        int x = minX + random.nextInt(bounds.getSize().getBlockWidth());
        int z = minZ + random.nextInt(bounds.getSize().getBlockLength());

        return new Location(world, x, minY, z);
    }

    public void playParticles(int amount, int offsetY, int rangeY) {
        ParticlePlayer particlePlayer = arena.getParticlePlayer();

        for (int i = 0; i < amount; i++) {
            particlePlayer.play(pickRandomLocation(offsetY, rangeY), 1);
        }
    }

    public Location pickRandomLocation(int offsetY, int rangeY) {

        int minX = bounds.getA().getBlockX();
        int minY = bounds.getA().getBlockY() + offsetY;
        int minZ = bounds.getA().getBlockZ();

        int x = minX + random.nextInt(size.getBlockWidth());
        int y = minY + (rangeY < 1 ? 0 : random.nextInt(rangeY));
        int z = minZ + random.nextInt(size.getBlockLength());

        return new Location(world, x, y, z);
    }

    public FloorPattern loadPattern(String name) {
        File file = new File(BlockParty.PLUGIN_FOLDER + "Floors/" + name + ".floor");
        try {
            FloorPattern pattern = PatternLoader.readFloorPattern(file);
            return pattern;
        } catch (FileNotFoundException e) {
            return null;
        } catch (FloorLoaderException e) {
            BlockParty.getInstance().getPlugin().getLogger().log(Level.SEVERE, "Could not load floor pattern \"" + name + "\"", e);
            return null;
        }
    }

}
